### ISSUE TITLE
Time Utils buggy with key inputs

### ISSUE THREAD

**Issue by khanshoaib3** [minecraft-access/minecraft-access#62]
The time utils while working fine the features that don't have any key input like the fall detector, it bugs out with the ones that have key inputs.
Many times when we press the key it is not registered likely because the timer is running and the interval is not ready.
To fix this, the timer should only start when there is a key input.

**Comment by boholder** [comment]
@khanshoaib3 I want to refactor the `Interval` class's `start` and `hasEnded` methods in #349 , I reproduce the bug (high speed executing when pressing the key), but I can't understand how your code fix the bug.
Can you explain a little more about how it works?

**Comment by khanshoaib3** [comment]
> @khanshoaib3 I want to refactor the `Interval` class's `start` and `hasEnded` methods in #349 , I reproduce the bug (high speed executing when pressing the key), but I can't understand how your code fix the bug.
> Can you explain a little more about how it works?

Sorry, which code? I don't see any line/file that I changed regarding the Interval class.

**Comment by boholder** [comment]
> I don't see any line/file that I changed regarding the Interval class.

That's because I moved this class, so all the lines are blamed on me.

What I want to refactor:
https://github.com/khanshoaib3/minecraft-access/blob/69502a15d9b391af2e704bf216dbaa2b2704735b/common/src/main/java/com/github/khanshoaib3/minecraft_access/utils/condition/Interval.java#L54-L73

Where they're used:
https://github.com/khanshoaib3/minecraft-access/blob/69502a15d9b391af2e704bf216dbaa2b2704735b/common/src/main/java/com/github/khanshoaib3/minecraft_access/features/CameraControls.java#L59-L68

TheSuperGamer20578 's suggestion:
https://github.com/khanshoaib3/minecraft-access/pull/349#discussion_r1792817063

**Comment by boholder** [comment]
@khanshoaib3 Please confirm the cause: https://github.com/khanshoaib3/minecraft-access/pull/349/commits/72c0a839659ef9726cdf3dee342211d661b8bdec

**Comment by khanshoaib3** [comment]
> @khanshoaib3 Please confirm the cause: https://github.com/khanshoaib3/minecraft-access/pull/349/commits/72c0a839659ef9726cdf3dee342211d661b8bdec

Oh yeah, there's no way to differentiate between nano and milli as both have the same data type. This change should fix the bug 👍
